Open Pull Request
hardcoderdev/Healther pull request #4
Opened 2023-02-19 13:25 UTC by hardcoderdev

Pull request for building _powerful_ _amazing_ _hyper cool_ **architecture**
@epicarchitect will be reviewer

2023-02-21 13:05 UTC, epicarchitect commented on settings.gradle.kts
> +include(":app")
и кажется ты забыл удалить src из папки app

2023-02-21 13:07 UTC, epicarchitect commented on app/android-ui/src/main/kotlin/hardcoder/dev/android_ui/setUpFlow/heroCreate/HeroCreateScreen.kt
> +    LaunchedEffect(key1 = Unit) {
а смысл скрина такого который просто ради того чтоб вызывать создания героя открывается. я думаю это надо убрать

2023-02-21 13:08 UTC, epicarchitect commented on app/android-ui/src/main/kotlin/hardcoder/dev/android_ui/waterTracking/create/SaveWaterTrackScreen.kt
> +                updateSelectedDrink = {
просто передавай функцию

2023-02-21 13:11 UTC, epicarchitect commented on app/android-ui/src/main/kotlin/hardcoder/dev/android_ui/CompositionsLocal.kt
> +val LocalDrinkTypeResources = compositionLocalOf<DrinkTypeResourcesProvider> {
ну LocalDrinkTypeResourcesProvider всетаки

2023-02-21 13:13 UTC, epicarchitect commented on app/database/src/main/kotlin/hardcoder/dev/database/AppDatabaseFactory.kt
> +            genderAdapter = EnumColumnAdapter()
в очередной раз хочу поинтересоваться что будет при обфускации сохраняться

2023-02-21 13:14 UTC, epicarchitect commented on app/database/src/main/sqldelight/hardcoder/dev/database/AppPreference.sq
> +import java.lang.Boolean;
а для чего импорт? у меня как то без него работает

2023-02-21 13:15 UTC, epicarchitect commented on app/database/src/main/sqldelight/hardcoder/dev/database/AppPreference.sq
> +    isFirstLaunch INTEGER AS Boolean NOT NULL
я тут подумал может лучше сохранять не isFirstLaunch а firstLaunchTime? типна будущее если что можно будет делать с этим временем что то, и определить естевенно верст лаунч тоже

2023-02-21 13:23 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/providers/AppPreferenceProvider.kt
> +import hardcoder.dev.database.AppPreference
лучше пропиши тут импорт алиас чтоб норм заимпортировать доменные преференсы

2023-02-21 13:24 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/providers/WaterTrackProvider.kt
> +    }
а я тут вспомнил что у каждого енама есть values() вот заюзай их

2023-02-21 13:25 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/providers/WaterTrackProvider.kt
> +    private fun WaterTrack.toEntity() = hardcoder.dev.entities.WaterTrack(
сделать норм импорт через импорт алиас

2023-02-21 13:26 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/creators/AppPreferenceCreator.kt
> +class AppPreferenceCreator(
я думаю тебе только апдейтер нужен для преференсов, а креатор не над

2023-02-21 13:28 UTC, epicarchitect commented on app/entities/src/main/kotlin/hardcoder/dev/entities/AppPreference.kt
> +    val id: Int,
айди ему тебе нужен только ради бд, однако у тебя преференсы вообще одни в приле, не нужен им айди

2023-02-21 13:35 UTC, epicarchitect commented on app/presentation/src/main/kotlin/hardcoder/dev/presentation/WaterTrackItemExt.kt
> +    drinkType = drinkType,
у тебя ведь дринк тайп есть внутри вотер трека

2023-02-21 13:38 UTC, epicarchitect commented on buildSrc/src/main/kotlin/Modules.kt
> +    object Paths {
если хочеш может как в хабитах заюзть TYPESAFE_PROJECT_ACCESSORS чтоб это тут все не писать

2023-02-21 13:40 UTC, epicarchitect commented on framework/extensions/src/main/kotlin/hardcoder/dev/extensions/LocalDateExt.kt
> +@SuppressLint("NewApi")
попробуй запусти свою прилу на апи 21, и скажи крашит тебя или нет) ну и прочитай что тебе пишет from которая крассным подчеркивает без этой анотации

2023-02-21 13:45 UTC, epicarchitect requested changes

2023-02-21 13:45 UTC, epicarchitect commented on framework/uikit/src/main/kotlin/hardcoder/dev/uikit/TextField.kt
> +package hardcoder.dev.uikit
у тебя разве OutlinedTextField где то используется?

2023-02-21 14:46 UTC, hardcoderdev commented on app/entities/src/main/kotlin/hardcoder/dev/entities/Hero.kt
> +    val id: Int,
Нужен, для update

2023-02-21 14:48 UTC, hardcoderdev commented on framework/uikit/src/main/kotlin/hardcoder/dev/uikit/TextField.kt
> +package hardcoder.dev.uikit
Нет, но будет

2023-02-22 16:01 UTC, epicarchitect commented on app/android-ui/src/main/kotlin/hardcoder/dev/android_ui/DrinkTypeResources.kt
> +data class DrinkTypeResources(
унести в фичу waterTracking

2023-02-22 16:07 UTC, epicarchitect commented on app/di/build.gradle.kts
> +    compileSdk = Android.compileSdk
а минимальный сдк = 1 тебя устраевает? ты знаеш какой у тебя minSdk стоит в во всех твоих модулях?

2023-02-22 16:09 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/hero/GenderIdMapper.kt
> +        else -> Gender.MALE
лучше бросать эксепшен вообще в ветке else тип так обычно делают в таких ситуациях

2023-02-22 16:11 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/hero/HeroUpdater.kt
> +        private const val HERO_ID = 0
юзай этот айди так же и в HeroCreator, сделай публичной эту константу но с модификатором internal. ну и вынеси от сюда куда нибудь в рамках этого пакета

2023-02-22 16:14 UTC, epicarchitect commented on app/di/build.gradle.kts
> +    api(project(Modules.Paths.logic))
тебе не надо тут подключать логик тк он идет у тебя с презентации

2023-02-22 16:15 UTC, epicarchitect commented on app/logic/src/main/kotlin/hardcoder/dev/logic/waterBalance/WaterTrackProvider.kt
> +    fun getAllDrinkTypes(): Flow<List<DrinkType>> {
дринк тайпы это не вотер треки, сделай для них отдельный провайдер, это же архитектура!

2023-02-22 16:18 UTC, epicarchitect commented on app/presentation/src/main/kotlin/hardcoder/dev/presentation/WaterTrackingViewModel.kt
> +        initialValue = hardcoder.dev.entities.Gender.MALE
а какой смысл херо вот так разбивать на несколько флоу? пусть будет один флоу херо и все

2023-02-22 16:19 UTC, epicarchitect commented on app/presentation/src/main/kotlin/hardcoder/dev/presentation/WaterTrackingViewModel.kt
> +        val gender: hardcoder.dev.entities.Gender,
импорт

2023-02-22 16:24 UTC, epicarchitect commented on app/di/build.gradle.kts
> +    api(project(Modules.Paths.logic))
и вприцнипе посмотри везде чтоб лишнего ничего не подключалось

2023-02-22 16:55 UTC, epicarchitect commented on app/entities/src/main/kotlin/hardcoder/dev/entities/Hero.kt
> +package hardcoder.dev.entities
в ентитях не так много классов сейчас и это не выглядит критично, но если хочешь то лучше разбить во фичам, waterTracking, hero, appPreferences

2023-02-23 18:58 UTC, merged